site_name: 我的博客
site_url: https://lovefruitmr64-tech.github.io/blog/

theme:
  name: material
  language: zh

  palette:

    - scheme: default
      toggle:
        icon: material/weather-sunny

    - scheme: slate
      toggle:
        icon: material/weather-night

plugins:
  - search:
      lang: zh

nav:
  - 首页: index.md

  - 博客:
      - 第一篇文章: posts/hello.md

copyright: Copyright &copy; 2020 - 2026 blog   #底部版权说明

extra:                                         #移除页脚“ Made with Material for MkDocs”的提示
  generator: false
